format = '''

[  î¼£](bold yellow) $directory$rust$package
[ ðŸ¦–](bold green) '''

scan_timeout = 10
add_newline = false
palette = 'foo'

[palettes.foo]
blue = '21'
mustard = '#af8700'

[directory]
style = "yellow"
home_symbol = " "
read_only = "ðŸ”’"
truncation_symbol = " â€¦/"
