format = '''

[  î¼£](bold yellow) $directory$rust$package$git_branch
[ ðŸ¦–](bold green) '''

scan_timeout = 10
add_newline = false
palette = 'foo'

[git_branch]
format = "[$symbol$branch]($style)"
symbol = "îœ¥ "
style = "bold yellow" 

[palettes.foo]
blue = '21'
mustard = '#af8700'

[directory]
style = "yellow"
home_symbol = ""
read_only = "ðŸ”’"
truncation_symbol = "â€¦/"
truncation_length = 2  
